# R: https://github.com/r-lib/actions/tree/v2/examples
#MARIADB: https://github.com/marketplace/actions/actions-setup-mysql

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:

  R-CMD-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes



    steps:
      - uses: shogo82148/actions-setup-mysql@v1.14.0
        with:
          mysql-version: 'mariadb-10.9'
          my-cnf: |
            [localhost]
            host=localhost
            user=testuser
            password=pwd

            [localhost2]
            host=127.0.0.1
            user=testuser
            password=wrongpwd

      - name: start db 
        run: |
          mysql -uroot -h127.0.0.1 -e 'SELECT version()'
      
      - name: make test db 
        run: |
          mysql -uroot -h127.0.0.1 -e "
            CREATE USER 'testuser'@'localhost' IDENTIFIED BY  'pwd';
            GRANT ALL ON *.* TO 'testuser'@'localhost';
            FLUSH PRIVILEGES ;
            CREATE DATABASE IF NOT EXISTS tests;
            "

      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
